FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY mime.types /etc/nginx/conf.d/mime.types

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
