version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - journal-network

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3001
    networks:
      - journal-network

networks:
  journal-network:
    driver: bridge
